
# Site settings
title: Artificial Intelligence and Statistics Conference
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "/aistats2009" # the subpath of your site, e.g. /blog/
url: "http://www.aistats.org" # the base hostname & protocol for your site
#twitter_username: aistat
github_username:  aistats
author:
  name: AISTATS
  email: aistats09@gmail.com
comments: false
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: aistats

ghub:
  edit: true
  repository: aistats2009

banner: resort.jpg

# Build settings
markdown: kramdown

conference:
  draft: false # set to True if the programme is draft only.
  image: main.jpg
  hide_tentative: true
  proceedings:
    url: http://proceedings.mlr.press/v5/
    show: true
  room: Room
  venue: Hilton Clearwater Beach Resort
  venue_url: http://www.clearwaterbeachresort.com/
  location: Clearwater Beach, Florida, USA
  full_name: Artificial Intelligence and Statistics
  short_name: AISTATS
  name: Artificial Intelligence and Statistics
  year: 2010
  instance: 12th
  styling: International Conference on
  dates:
  - 2009-04-16
  - 2009-04-18
  chairs:
  - type: Program Chairs
    people:
    - family: David
      given: van Dyk
      institute: University of California, Irvine
      url: http://www.ics.uci.edu/~dvd/
    - family: Welling
      given: Max
      institute: University of California, Irvine
      url: http://www.ics.uci.edu/~welling
  - type: Fundraising Chair
    people:
    - family: Sutton
      given: Charles
      institute: University of Edinburgh
  - type: Publicity Chair
    people:
    - family: Ihler
      given: Alexander
      institute: University of California, Irvine
  - type: Publications Chair
    people:
    - family: Alvarez
      given: Mauricio
      institute: University of Manchester

# change encoding for the generated output files to utf-8
encoding: utf-8


